# Generated by Django 4.1.5 on 2023-03-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_api_user_apimethods_user_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='user',
        ),
        migrations.RemoveField(
            model_name='apimethods',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='api',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
