# Generated by Django 4.1.5 on 2023-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_product_store_product_brand_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
