# Generated by Django 4.1.5 on 2023-03-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_api_user_remove_apimethods_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='api',
            new_name='store',
        ),
    ]
