# Generated by Django 4.1.5 on 2023-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_api_api_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimethods',
            name='auth',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apimethods',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apimethods',
            name='header',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apimethods',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
